name: 'Setup Android NDK'
description: 'Setup an Android NDK environment by downloading and returning it via ndk-path'
author: 'Raphaël Thériault'
inputs:
  ndk-version:
    description: 'Exact version to use'
    required: true
  add-to-path:
    description: 'Add installation directory to path'
    required: false
    default: 'true'
outputs:
  ndk-path:
    description: 'Installation path'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'green'
